### ISSUE TITLE
Devices keeps disconnecting on 2.4Ghz band

### ISSUE THREAD

**Issue by mgupta80** [dangowrt/owrt-ubi-installer#92]
Hi, My Nest IQ outdoor cameras keeps disconnecting very frequently. They only support 2.4 GHz wifi band in UK, I have also tried giving them a static IP address but that didn't helped either. 

Could someone please suggest if they are having a similar issue and are there any logs that might be useful for debugging?

<img width="958" alt="image" src="https://user-images.githubusercontent.com/52509658/164111276-cd0875b6-406b-4d70-a99d-c777798a019f.png">

**Comment by dangowrt** [comment]
Please discuss this in the [OpenWrt forums](https://forum.openwrt.org) -- this repository is merely the installer and that has apparently worked well for you :wink:

**Comment by neilsan1366** [comment]
do you have found a solution because i has same problem unfortunatly i'm desesperate

**Comment by mrkiko** [comment]
The problem is not related to this repository, which provides an installer to convert this device to UBI layout with a fresh bootchain with great features.
Your problem might bebetter discussed in the OpenWRt forum as suggested, maybe after trying to install the latest master snapshot for ubi layout!
